### ISSUE TITLE
Start issue

### ISSUE THREAD

**Issue by farfeduc** [fatihky/c9-manager#1]
Hi,

When I start `node app`, I get : 

``` bash
c9-manager/app.js:10
  .then(port => {
             ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I didn't find anything useful on that and didn't find any typo issues. 

I am running on Ubuntu 15.10 with node 0.12.6 and npm 3.8.1.

I hope there is a solution to this because I was really looking forward to it.

**Comment by fatihky** [comment]
You must use node `v4.x.x` or later.  But I will change these lines so you will be able to use `c9-manager` with node `0.12.x`.

**Comment by fatihky** [comment]
I have tried current(updated) app with `v0.12.9` and looks like it works. Let me know any other issues.

**Comment by farfeduc** [comment]
I have just copied the config.sample.js to config.js and when I start the app, the console shows  : 

``` bash
port: 6321
6321 null []
```

But the real port is : 6320.

And when I try to connect to : http://localhost:6320 there is only : 

`Cannot GET /` on the page.

**Comment by fatihky** [comment]
Sorry for poor documentation.
1. First log is just for debugging purposes probably.
2. You can see your ides at `/ides` page.

**Comment by fatihky** [comment]
I have added some commits about your new comment. I have removed that `console.log`.

**Comment by farfeduc** [comment]
Ok, no problem ;)

Here is what I get when I try to start a new ide : 

``` bash

Application listening on http://localhost:6320
Go to the http://localhost:6320/ides to see and manage your ides.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn daemonize ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

```

Is it some issue with my installation of c9 ? I have the folder in /opt/c9sdk like you asked.

**Comment by farfeduc** [comment]
I have checked, the directory exists.

Do I need to precise some port or do I need to do something particular ?

**Comment by fatihky** [comment]
You need to install [daemonize](https://github.com/bmc/daemonize). I will add this information to the readme.

**Comment by farfeduc** [comment]
It works. :)

Now I can start and remove ides. The only issue remaining might not be related to your app.

My idea seems to start good but the page is almost blank. Like it didn't had the permission to load the assets.
I will search.

**Comment by fatihky** [comment]
If you mean `/ides` page, it has not assets(css, js etc...).

**Comment by fatihky** [comment]
I am closing the issue. Thanks for your interest.
